# Generated by Django 3.1.7 on 2021-04-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0002_remove_survey_date_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='date_created',
            new_name='date',
        ),
    ]
