# Generated by Django 3.1.7 on 2021-06-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0003_auto_20210421_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name_plural': 'Surveys'},
        ),
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
